
---

- hosts: all
  become: True
  tasks:

    - name: block ip address in ubuntu
      ufw:
        rule: allow
        proto: any
        from_ip: 192.168.56.135
      when: ansible_distribution == "Ubuntu"

    - name: block ip address in centos
      firewalld:
        permanent: true
        state: enabled
        zone: public
        source: 192.168.56.132
      when: ansible_distribution == "Centos"

    - block:

      - name: checking firewall in ubuntu
        shell: sudo ufw status
        register: ufw_stat
        when: ansible_distribution == "Ubuntu"

      - debug: 
          msg="{{ ufw_stat }}"

    - block:

      - name: checking firewall in centos
        command: sudo firewall-cmd --zone=public --list-all
        register: firewalld_stat
        when: ansible_distribution == "Centos"

      - debug: 
          msg="{{ firewalld_stat }}"

